watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ['primary']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false # Blur effect will be applied to the bar
      acrylic: false # Acrylic effect will be applied to the bar
      dark_mode: false # Dark mode will also add more shadow to the bar
      round_corners: false # Default radius from OS
      border_color: None # If is None border will be removed, System will use OS accent color, otherwise you can set your own HEX color (this option is related to round_corners=true)
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
          "komorebi_workspaces",
          "komorebi_active_layout",
          "active_window",
      ]
      center: [
          "clock",
        ]
      right: [
          "media",
          "memory",
          "volume",
          "power_menu",
      ]
widgets:
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      max_field_size:
        label: 30
        label_alt: 24
      show_thumbnail: false
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 250
      thumbnail_padding: 0
      thumbnail_corner_radius: 0
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label_alt: "<span>î¿…</span> {virtual_mem_free} / {virtual_mem_total}"
      label: "<span>\uf4bc</span> {virtual_mem_outof}"
      update_interval: 10000
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {time_remaining}"
      update_interval: 30000
      hide_unsupported: true
      charging_options:
        icon_format: "{charging_icon}"
      status_icons:
        icon_charging: "ó°‚„"
        icon_critical: "ó°º"
        icon_low: "ó°»"
        icon_medium: "ó°½"
        icon_high: "ó°¿"
        icon_full: "ó°‚"
      callbacks:
        on_left: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:batterysaver"

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        [
          "bsp",
          "columns",
          "rows",
          "grid",
          "vertical_stack",
          "horizontal_stack",
          "ultrawide_vertical_stack",
          "right_main_vertical_stack",
        ]
      layout_icons:
        bsp: "BSP"
        columns: "COL"
        rows: "ROW"
        grid: "GRID"
        vertical_stack: "VST"
        horizontal_stack: "HST"
        ultrawide_vertical_stack: "WST"
        right_main_vertical_stack: "RMV"
        monocle: "MONO"
        maximized: "MAX"
        floating: "FLT"
        paused: "PAUSE"
      callbacks:
        on_left: "next_layout"
        on_middle: "toggle_monocle"
        on_right: "prev_layout"

  network:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>ó°–©</span> {wifi_name}"
      label_alt: "<span>{wifi_icon}</span> {wifi_name} {wifi_strength}%"
      update_interval: 5000
      ethernet_label: "<span>ó°ˆ€</span> Ethernet"
      ethernet_label_alt: "<span>ó°ˆ€</span> Ethernet"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:network"
      menu_config:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\udb80\udd50</span> {%a, %d %b %H:%M}"
      label_alt: "<span>\udb80\udd50</span> {%A, %d %B %Y %H:%M}"
      timezones: []
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "Komorebi Offline"
        label_workspace_btn: "{index}"
        label_workspace_active_btn: "{index}"
        label_workspace_populated_btn: "{index}"
        label_default_name: "{index}"
        label_zero_index: false
        hide_empty_workspaces: false
        hide_if_offline: false
        animation: true
        container_padding:
          top: 0
          left: 8
          bottom: 0
          right: 8

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts: ['bsp', 'columns', 'rows', 'grid', 'vertical_stack', 'horizontal_stack', 'ultrawide_vertical_stack','right_main_vertical_stack']
      layout_icons:
        bsp: "BSP"
        columns: "COLS"
        rows: "ROWS"
        grid: "GRID"
        vertical_stack: "V-STACK"
        horizontal_stack: "H-STACK"
        ultrawide_vertical_stack: "W-STACK"
        right_main_vertical_stack: "RMV-STACK"
        monocle: "MONOCLE"
        maximised: "MAX"
        floating: "FLOATING"
        paused: "PAUSED"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      callbacks:
        on_left: 'next_layout'
        on_middle: 'toggle_monocle'
        on_right: 'prev_layout'
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 250 # Milisecond
      button_row: 3 # Number of buttons in row, min 1 max 5
      buttons:
        lock: ["\uea75","Lock"]
        signout: ["\udb80\udf43","Sign out"]
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        hibernate: ["\uf28e","Hibernate"]
        cancel: ["\udb81\udf3a","Cancel"]